/* ============================================================
   Brand — Chickadee (open-core build).
   GENERATED by chickadee-addons/scripts/sync-console.sh at vendor
   time (dashie-console @ 90bac93) — do not edit by hand.

   Wire values deliberately stay Dashie's (see the Dashie brand.js
   header): the `dashie_cloud` engine ID, localStorage keys,
   dashie-* CSS classes, and option/wake-word IDs are contracts,
   not brand. Only display identity changes here.
   ============================================================ */

const BRAND = {
    // 'chickadee' flips FeatureGate's open-build rules (family pages off,
    // voice/AI + credits ungated). Absent in the Dashie brand.js.
    build: 'chickadee',

    // Product + assistant naming
    productName: 'Chickadee',
    consoleName: 'Chickadee Console',
    assistantName: 'Chickadee',
    wakePhrase: 'your wake word',    // HA pipelines bring their own wake word
    cloudName: 'Chickadee Cloud',    // display label for the `dashie_cloud` engine
    teamName: 'the Chickadee team',

    // Web presence — accounts/billing ride the Dashie backend (footer
    // honesty: the Dashie connection is documented, not hidden).
    domain: 'dashieapp.com',
    supportEmail: 'support@dashieapp.com',

    // Brand assets (paths relative to the console root)
    logo: 'assets/chickadee-logo.png',
    icon: 'assets/chickadee-icon.png',

    // Docs / legal
    urls: {
        privacy: 'https://dashieapp.com/privacy-policy.html',
        terms: 'https://dashieapp.com/terms-of-service.html',
    },
};

// Keep the tab identity brand-driven (index.html ships Dashie fallbacks).
try {
    document.title = BRAND.consoleName;
    const fav = document.querySelector('link[rel="icon"]');
    if (fav) fav.href = BRAND.icon;
} catch (_) { /* non-browser */ }

window.BRAND = BRAND;
