/* ============================================================
   AUTO-GENERATED — DO NOT EDIT BY HAND
   ------------------------------------------------------------
   Source of truth:
     js/ai/prompts/freeform-prompt.js
   Generated by:
     dashieapp_staging/scripts/bundle-ai-prompts.js
   To update: edit the source(s) above and run
       node scripts/bundle-ai-prompts.js
   (or just release the add-on — scripts/release.sh runs this first).
   ============================================================ */

// CommonJS build for the add-on server. The browser build of the same source
// lives at frontend/console/js/lib/ — one source, two runtimes, no mirror.
// js/ai/prompts/freeform-prompt.js
//
// FreeformPrompt — the text assembly for the console's Freeform mode AND for the
// add-on brain that actually sends it.
//
// 🔴 THIS FILE IS THE SOURCE OF TRUTH FOR THREE RUNTIMES.
// `scripts/bundle-ai-prompts.js` generates:
//   • dashie-ha-console .../frontend/console/js/lib/freeform-prompt.js  (browser IIFE)
//   • dashie-ha-console .../server/freeform-prompt.js                   (CommonJS)
// Never hand-edit either output; `--check` fails the build if they drift.
//
// WHY it is shared rather than mirrored (JS_KOTLIN_CONTRACTS row 183): the console's
// Raw view is sold to the user as "everything that will be sent", and the add-on is
// what sends. Two copies means the preview is a confident non-answer — a complete,
// plausible prompt that is not the prompt. The row said this should become tier 1
// (eliminate) rather than stay a gated hand-mirror; generating both outputs from
// this file is that elimination.
//
// ── THE ORDER IS HOME ASSISTANT'S, DELIBERATELY ─────────────────────────────────
// Copied from HA core 2026.9.3, components/conversation/chat_log.py
// (async_provide_llm_data):
//
//     prompt_parts = [ render(user_prompt or DEFAULT_INSTRUCTIONS_PROMPT),
//                      llm_api.api_prompt,
//                      DATE_TIME_PROMPT   # only when no GetDateTime tool,
//                      extra_system_prompt ]
//
// The user's text is FIRST and nothing structural follows it. Tool schemas appear
// nowhere in the prompt — they go to the model as declarations — which is why
// nothing a user writes can break them.
//
// ── WHY THE DEFAULT BOX IS NOT EMPTY ───────────────────────────────────────────
// HA's own default is three lines (helpers/llm.py DEFAULT_INSTRUCTIONS_PROMPT),
// verified against the installed 2026.9.3 package, not a blank box — an empty
// textarea teaches nobody that Jinja works here. Ours mirrors theirs and adds one
// templated line.

/** Mirrors HA's DEFAULT_INSTRUCTIONS_PROMPT, with our one Jinja example. */
const DEFAULT_TEMPLATE =
    'You are the voice assistant for {{ ha_name }}.\n'
    + 'Answer questions about the world truthfully.\n'
    + 'Respond simply and to the point in plain text.\n';

/**
 * The starting text when someone switches Dynamic → Freeform.
 *
 * House rules come WITH them (John, 2026-10-04). They are the same thing in both
 * modes — a few standing lines the household wants obeyed — so dropping them at the
 * switch would quietly discard work the user had already done, and would hand them a
 * near-empty box when they have already said what they want. Carried, not copied:
 * editing the box afterwards does not write back.
 */
function seed(houseRules) {
    const rules = String(houseRules || '').trim();
    return rules ? `${DEFAULT_TEMPLATE}\n${rules}\n` : DEFAULT_TEMPLATE;
}

/** Has the user actually written something, or is this still the seed? */
function isUntouched(prompt, houseRules) {
    return String(prompt || '').trim() === seed(houseRules).trim();
}

/**
 * The assembled prompt: everything that will be sent, in send order.
 *
 * `rendered` is HA's answer for the user's template — Jinja is never rendered here,
 * so what this returns is what HA produced, including its whitespace. When the
 * template has not been rendered yet the caller passes the raw text with
 * `pending: true`, and the result says so rather than presenting un-substituted
 * braces as if they were final.
 *
 * 🔴 `catalog` IS INJECTED, NOT READ FROM A GLOBAL. The first version read
 * `window.PromptToolCatalog`, which is undefined in node — so the add-on, the one
 * runtime that actually sends this prompt, would have silently assembled it with no
 * tools and no live-context line. A browser caller passes window.PromptToolCatalog;
 * the add-on passes its required copy.
 */
function raw({ rendered, personalityText, toolsStored, dateLine, pending, catalog }) {
    const parts = [];
    parts.push(String(rendered || '').trimEnd());
    if (personalityText) parts.push(String(personalityText).trim());

    // One behavior line per capability that needs the model to KNOW it has it.
    // Modelled on HA's DYNAMIC_CONTEXT_PROMPT, whose whole job is to stop the model
    // claiming it cannot read live state. Guidance, never a format rule — the format
    // lives in the declarations.
    const ids = catalog ? catalog.parse(toolsStored) : [];
    if (ids.includes('live_context')) {
        parts.push('You can read the current state of this home with dashie__GetLiveContext.\n'
            + 'Do not say you lack that ability.');
    }

    // HA appends date/time ONLY when no clock tool is present, so a fact is either a
    // tool or a prompt line and never both.
    if (dateLine) parts.push(dateLine);

    const sigs = catalog ? catalog.signatures(toolsStored) : '';
    if (sigs) parts.push(`TOOLS\n${sigs}`);

    const body = parts.filter(Boolean).join('\n\n');
    return pending ? `[not rendered yet — press Render]\n\n${body}` : body;
}

/** The date line HA would append, in HA's own wording. */
function dateLine(now = new Date()) {
    const t = now.toTimeString().slice(0, 8);
    const d = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
    return `Current time is ${t}. Today's date is ${d}.`;
}

module.exports = {
    DEFAULT_TEMPLATE,
    seed,
    isUntouched,
    raw,
    dateLine,
};
