#!/usr/bin/env bash
# Vendor the dashie-console SPA into the Chickadee add-on as the Chickadee
# console, applying the Chickadee brand at vendor time.
#
# INTERIM DIRECTION (see chickadee CONTRACTS.md): today the closed
# dashie-console repo is upstream and Chickadee vendors a branded copy.
# The open-core plan's Phase 4 "repo inversion" flips this — the Chickadee
# console becomes the upstream and dashie-console the private delta. Until
# then this script is the whole relationship; don't mistake the vendored
# tree for original source.
#
# Exports the COMMITTED tree of a dashie-console branch via `git archive`
# (same rationale as the dashie add-on's sync-console.sh: no branch switch,
# no uncommitted-file contamination, no .git/node_modules), then:
#   1. replaces js/lib/brand.js with the generated Chickadee brand
#      (build: 'chickadee' — flips FeatureGate's open-build gating)
#   2. copies the Chickadee logo/icon into assets/
#
# Usage:
#   ./scripts/sync-console.sh [branch] [console-path]
#     branch        dashie-console branch to vendor (default: main)
#     console-path  local dashie-console clone (default: ../dashie-console)

set -euo pipefail

BRANCH="${1:-main}"
CONSOLE_PATH="${2:-$(cd "$(dirname "$0")/../.." && pwd)/dashie-console}"
ADDON_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="$ADDON_ROOT/chickadee/frontend/console"

if [[ ! -d "$CONSOLE_PATH/.git" ]]; then
    echo "Error: $CONSOLE_PATH is not a git repository." >&2
    echo "Pass the path to your local dashie-console clone as the second argument." >&2
    exit 1
fi

echo "==> Fetching dashie-console origin/$BRANCH" >&2
git -C "$CONSOLE_PATH" fetch origin "$BRANCH" --quiet
CONSOLE_SHA="$(git -C "$CONSOLE_PATH" rev-parse --short "origin/$BRANCH")"

echo "==> Vendoring origin/$BRANCH ($CONSOLE_SHA) → $TARGET" >&2
rm -rf "$TARGET"
mkdir -p "$TARGET"
git -C "$CONSOLE_PATH" archive "origin/$BRANCH" | tar -x -C "$TARGET"

echo "==> Applying Chickadee brand (js/lib/brand.js + assets)" >&2
cp "$ADDON_ROOT/chickadee/logo.png" "$TARGET/assets/chickadee-logo.png"
cp "$ADDON_ROOT/chickadee/icon.png" "$TARGET/assets/chickadee-icon.png"
# Static fallbacks brand.js only fixes after load — avoid the Dashie flash.
sed -i.bak -e 's|<title>Dashie Console</title>|<title>Chickadee Console</title>|' \
    -e 's|href="assets/dashie-icon.png"|href="assets/chickadee-icon.png"|' "$TARGET/index.html"
rm -f "$TARGET/index.html.bak"

cat > "$TARGET/js/lib/brand.js" <<EOF
/* ============================================================
   Brand — Chickadee (open-core build).
   GENERATED by chickadee-addons/scripts/sync-console.sh at vendor
   time (dashie-console @ $CONSOLE_SHA) — do not edit by hand.

   Wire values deliberately stay Dashie's (see the Dashie brand.js
   header): the \`dashie_cloud\` engine ID, localStorage keys,
   dashie-* CSS classes, and option/wake-word IDs are contracts,
   not brand. Only display identity changes here.
   ============================================================ */

const BRAND = {
    // 'chickadee' flips FeatureGate's open-build rules (family pages off,
    // voice/AI + credits ungated). Absent in the Dashie brand.js.
    build: 'chickadee',

    // Product + assistant naming
    productName: 'Chickadee',
    consoleName: 'Chickadee Console',
    assistantName: 'Chickadee',
    wakePhrase: 'your wake word',    // HA pipelines bring their own wake word
    cloudName: 'Chickadee Cloud',    // display label for the \`dashie_cloud\` engine
    teamName: 'the Chickadee team',

    // Web presence — accounts/billing ride the Dashie backend (footer
    // honesty: the Dashie connection is documented, not hidden).
    domain: 'dashieapp.com',
    supportEmail: 'support@dashieapp.com',

    // Brand assets (paths relative to the console root)
    logo: 'assets/chickadee-logo.png',
    icon: 'assets/chickadee-icon.png',

    // Docs / legal
    urls: {
        privacy: 'https://dashieapp.com/privacy-policy.html',
        terms: 'https://dashieapp.com/terms-of-service.html',
    },
};

// Keep the tab identity brand-driven (index.html ships Dashie fallbacks).
try {
    document.title = BRAND.consoleName;
    const fav = document.querySelector('link[rel="icon"]');
    if (fav) fav.href = BRAND.icon;
} catch (_) { /* non-browser */ }

// Chickadee theme: brand wing-blue accent (#2C6ECE, sampled from the logo's
// wing) replaces Dashie orange. The console is fully accent-var driven, so
// four variable overrides re-skin everything (preset outlines/checkmarks,
// toggles, tabs, active nav, primary buttons); the one exception is the
// active nav-icon tint, which is a CSS filter (filters can't read vars) —
// overridden with a blue-producing chain. Injected AFTER the stylesheets
// (brand.js is the first <script>, below the <link>s) so equal-specificity
// rules win by order; the vendored CSS stays byte-identical to upstream.
try {
    const theme = document.createElement('style');
    theme.textContent = [
        ':root {',
        '  --accent: #2C6ECE;',
        '  --accent-hover: #2559A8;',
        '  --accent-bg: rgba(44, 110, 206, 0.08);',
        '  --accent-bg-hover: rgba(44, 110, 206, 0.14);',
        '}',
        '.sidebar-nav-item.active .nav-icon img {',
        '  filter: brightness(0) saturate(100%) invert(36%) sepia(78%) saturate(1350%) hue-rotate(203deg) brightness(94%) contrast(92%);',
        '}',
    ].join('\n');
    document.head.appendChild(theme);
} catch (_) { /* non-browser */ }

window.BRAND = BRAND;
EOF

echo "==> Synced dashie-console origin/$BRANCH @ $CONSOLE_SHA (Chickadee brand applied)" >&2
# Emit ONLY the source SHA on stdout so release.sh can capture it.
echo "$CONSOLE_SHA"
